name: Container Scan - Trivy

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  schedule:
    - cron: "0 17 * * 5"

# workflow
permissions:
  contents: read
  security-events: write

jobs:
  trivy-postgres:
    name: Scan postgres image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # clone repo

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: postgres:17-alpine
          format: sarif
          output: trivy-postgres.sarif
          severity: CRITICAL,HIGH
          vuln-type: os,library
          ignore-unfixed: true

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-postgres.sarif
          category: trivy-postgres

  trivy-backend:
    name: Scan backend image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # clone repo

      - name: Create dummy .env for build
        run: echo "DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy" > server/.env

      - name: Build image with docker compose
        run: docker compose build server

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: gr_server
          format: sarif
          output: trivy-backend.sarif
          severity: CRITICAL,HIGH
          vuln-type: os,library
          ignore-unfixed: true

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-backend.sarif
          category: trivy-backend

  trivy-frontend:
    name: Scan frontend image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build image with docker compose
        run: docker compose build client

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: gr_client
          format: sarif
          output: trivy-frontend.sarif
          severity: CRITICAL,HIGH
          vuln-type: os,library
          ignore-unfixed: true

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-frontend.sarif
          category: trivy-frontend